"""update_password_reset_token

Revision ID: 73dec2fadf90
Revises: 
Create Date: 2025-12-12 21:33:30.937016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73dec2fadf90'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_reset_tokens', sa.Column('token_hash', sa.String(length=255), nullable=False))
    op.drop_column('password_reset_tokens', 'otp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_reset_tokens', sa.Column('otp', sa.VARCHAR(length=6), autoincrement=False, nullable=False))
    op.drop_column('password_reset_tokens', 'token_hash')
    # ### end Alembic commands ###
